ignored:
  # Не требуем pin-версию пакетов apt-get (если бы мы их использовали)
  - DL3008
  # Пример: игнорируем правило про отсутствие LABEL maintainer
  - DL4006

failure-threshold: warning   # предупреждения не валят сборку, только ошибки
format: tty
